Tiberiade\MainBundle\Entity\Utilisateur:
    type: entity
    table: utilisateurs
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
        password:
            type: string
        nom:
            type: string
        prenom:
            type: string
        email:
            type: string
        role:
            type: string